In [1]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)


tensor([[0.9090, 0.2474, 0.0491],
        [0.1983, 0.1753, 0.1836],
        [0.1261, 0.2791, 0.6294],
        [0.6655, 0.4192, 0.2563],
        [0.2575, 0.6029, 0.3515]])


In [2]:
'''Construct a randomly initialized matrix: '''
x = torch.rand(5, 3)
print(x)

tensor([[2.3310e-01, 1.3109e-01, 8.5161e-01],
        [4.0107e-01, 9.5246e-01, 8.9331e-01],
        [2.8151e-01, 3.7427e-02, 3.5107e-04],
        [9.3368e-01, 1.8639e-01, 6.7814e-01],
        [2.7127e-02, 9.3950e-01, 6.8572e-01]])


In [3]:
'''Construct a matrix filled zeros and of dtype long:'''
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
'''Construct a tensor directly from data:'''
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])
